use crate::types::PreprocessorType;

pub enum LiteralType {
    Integer,
    Float,
    String,
    Boolean,
    Array,
    Null,
}

#[derive(Debug)]
pub enum NodeType {
    Program,
    VariableDeclaration,
    ArrayDeclaration,
    PointerDeclaration,
    PointerDeref,
    FunctionDeclaration,
    FunctionDeclarationArgument,
    FunctionDeclarationArguments,
    VariableAssignment,
    ArrayAssignment,
    ArrayElementAssignment,
    ArrayExpression,
    ArrayElement,
    Identifier,
    Type,
    Scope,
    ReturnStatement,
    BinaryOperator,
    UnaryOperator,
    Expression,
    IfStatement,
    ElifStatement,
    ElseStatement,
    WhileStatement,
    DoStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,
    FunctionCall,
    FuntionCallArgument,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    BooleanLiteral,
    NullLiteral,
    PreprocessorStatement(PreprocessorType),
}
